# Generated by Django 5.0 on 2024-01-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_wishlist_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
